#pragma once
#include <map>
#include <string>
#include "../trigger-engine/core/game/component.h"
#define regi_component(type) trigger::manager::class_manager::regi_component<type>(#type);
//DO NOT EDIT THIS FILE!
#include "src/material/material.h"

//Regist Component
static void reload(){
	regi_component(material);
}
