#pragma once
#include <map>
#include <string>
#include "../trigger-engine/core/game/class_manager.h"
#define regi_component(type) trigger::component::regi_component<type>(#type);
//DO NOT EDIT THIS FILE!

//Regist Component
static void reload(){
}
