#pragma once
#include <map>
#include <string>
#include "../trigger-engine/core/game/component.h"
#define regi_component(type) regi_component<type>(#type);
//DO NOT EDIT THIS FILE!

//Regist Component
static void reload(){
}
